services:
  traefik:
    image: traefik:v2.11
    restart: always
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--providers.file.filename=/etc/traefik/tls.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"

    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./traefik-tls.yml:/etc/traefik/tls.yml:ro

  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    # Uncomment to build the image from the Dockerfile for local testing changes.
    # Remember to comment out the image line above.
    #build: .
    container_name: calibre-web-automated-book-downloader
    environment:
      FLASK_PORT: 8084
      LOG_LEVEL: info
      BOOK_LANGUAGE: en
      USE_BOOK_TITLE: true
      TZ: America/New_York
      APP_ENV: prod
      UID: 1000
      GID: 100
      # CWA_DB_PATH: /auth/app.db  # Comment out to disable authentication
      # Queue management settings
      MAX_CONCURRENT_DOWNLOADS: 3
      DOWNLOAD_PROGRESS_UPDATE_INTERVAL: 5
    networks:
      - web
    restart: unless-stopped
    volumes:
      # This is where the books will be downloaded to, usually it would be
      # the same as whatever you gave in "calibre-web-automated"
      - /tmp/data/calibre-web/ingest:/cwa-book-ingest
      # This is the location of CWA's app.db, which contains authentication
      # details. Comment out to disable authentication
      #- /cwa/config/path/app.db:/auth/app.db:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.rule=PathPrefix(`/add-books/`)"
      - "traefik.http.routers.calibre.entrypoints=websecure"
      - "traefik.http.routers.calibre.tls=true"
      - "traefik.http.services.calibre.loadbalancer.server.port=8084"
      - "traefik.docker.network=web"

networks:
  web:
    external: true
