services:
  traefik:
    image: traefik:v2.11
    restart: always
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--providers.file.filename=/etc/traefik/tls.yml"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"
      - "--accesslog=true"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./traefik-tls.yml:/etc/traefik/tls.yml:ro

  shelfmark:
    image: ghcr.io/calibrain/shelfmark:latest
    container_name: shelfmark
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cwab.rule=Host(`www.homelibrary.me`) && PathPrefix(`/add-books/`)"
      - "traefik.http.routers.cwab.entrypoints=websecure"
      - "traefik.http.routers.cwab.middlewares=cwab-strip"
      - "traefik.http.routers.cwab.tls=true"
      - "traefik.http.middlewares.cwab-strip.stripprefix.prefixes=/add-books"
      - "traefik.http.services.cwab.loadbalancer.server.port=8084"
    environment:
      PUID: 1000
      PGID: 100
      FLASK_PORT: 8084
      TZ: America/New_York
      URL_BASE: /add-books
    networks:
      - web
    restart: unless-stopped
    # port 8084 is handled by Traefik
    volumes:
      - /tmp/data/calibre-web/ingest:/books
      - /path/to/config:/config

networks:
  web:
    external: true
