tls:
  certificates:
    - certFile: /certs/calibre.crt
      keyFile: /certs/calibre.key

http:
  routers:
    main:
      rule: "Host(`homelibrary.me`)"
      entryPoints:
        - websecure
      service: main-service
      tls: {}

  services:
    main-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8083"
