tls:
  certificates:
    - certFile: /certs/calibre.crt
      keyFile: /certs/calibre.key

http:
  routers:
    main:
      rule: "Host(`www.homelibrary.me`)"
      entryPoints:
        - websecure
      service: main-service
      tls: {}
    addbooks:
      rule: "Host(`www.homelibrary.me`)"
      entryPoints:
        - addbooks
      service: addbooks-service
      tls: {}

  services:
    main-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8083"
    addbooks-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8084"
